import type { CivicReport } from './types';

export const demoReports: CivicReport[] = [
  {
    id: 'r1',
    title: 'Large pothole on residential road',
    description: 'AI detected a large road-surface failure affecting approximately one traffic lane near a school crossing.',
    imageUrl: 'https://images.unsplash.com/photo-1621969737145-d3e8d39e6f6b?q=80&w=1200&auto=format&fit=crop',
    latitude: 40.7138,
    longitude: -74.006,
    category: 'Road Infrastructure',
    severity: 'Critical',
    impactScore: 91,
    priority: 'Critical',
    department: 'Roads & Transport',
    estimatedResolution: '3-5 days',
    status: 'Assigned',
    createdAt: '2026-07-12T10:00:00Z',
    confidence: 94,
    impactReason: 'Located on a busy residential road and creates a high accident risk for cyclists, drivers, and pedestrians during rainfall.',
    aiExplanation: 'The image shows a deep asphalt cavity with broken road edges and likely water accumulation risk.',
    potentialConsequences: 'If ignored, the pothole may increase accident risk, damage vehicles, and worsen during heavy rainfall.',
    immediateAction: 'Install warning signage, cone off the lane edge, and schedule a road inspection crew.',
    communityConfidence: 87,
    confirmations: 23,
    evidenceCount: 5,
    safetyRisk: 'High',
    accessibilityImpact: 'Medium',
    environmentalImpact: 'Low',
    peopleAffected: 'Estimated 200+',
  },
  {
    id: 'r2',
    title: 'Overflowing public garbage bins',
    description: 'Waste overflow and suspected illegal dumping next to a busy park entrance.',
    imageUrl: 'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?q=80&w=1200&auto=format&fit=crop',
    latitude: 40.718,
    longitude: -74.012,
    category: 'Waste Management',
    severity: 'High',
    impactScore: 78,
    priority: 'High',
    department: 'Waste Management',
    estimatedResolution: '24-48 hours',
    status: 'In Progress',
    createdAt: '2026-07-13T14:30:00Z',
    confidence: 91,
    impactReason: 'High foot traffic and environmental exposure create sanitation and pest risks.',
    aiExplanation: 'Visible overflow exceeds bin capacity and waste has spread into public walking space.',
    potentialConsequences: 'If ignored, the site may attract pests, create odors, and discourage park use.',
    immediateAction: 'Dispatch sanitation pickup and inspect for recurring illegal dumping patterns.',
    communityConfidence: 81,
    confirmations: 14,
    evidenceCount: 3,
    safetyRisk: 'Medium',
    accessibilityImpact: 'Low',
    environmentalImpact: 'High',
    peopleAffected: 'Estimated 500+',
  },
  {
    id: 'r3',
    title: 'Broken streetlight at bus stop',
    description: 'Lighting outage creates unsafe waiting conditions after dark at a transit stop.',
    imageUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?q=80&w=1200&auto=format&fit=crop',
    latitude: 40.709,
    longitude: -74.001,
    category: 'Public Safety',
    severity: 'Medium',
    impactScore: 66,
    priority: 'Medium',
    department: 'Electricity',
    estimatedResolution: '2-4 days',
    status: 'Verified',
    createdAt: '2026-07-14T20:10:00Z',
    confidence: 88,
    impactReason: 'Reduced nighttime visibility affects transit riders and nearby pedestrians.',
    aiExplanation: 'The scene indicates inadequate illumination around a waiting area.',
    potentialConsequences: 'If ignored, riders may face increased safety risks and lower transit confidence.',
    immediateAction: 'Log a lighting repair order and prioritize inspection before evening commute.',
    communityConfidence: 74,
    confirmations: 8,
    evidenceCount: 2,
    safetyRisk: 'Medium',
    accessibilityImpact: 'Medium',
    environmentalImpact: 'Low',
    peopleAffected: 'Estimated 120+',
  },
  {
    id: 'r4',
    title: 'Water leak flooding sidewalk',
    description: 'Continuous water leak is pooling on the sidewalk and flowing toward a storm drain.',
    imageUrl: 'https://images.unsplash.com/photo-1544531586-fde5298cdd40?q=80&w=1200&auto=format&fit=crop',
    latitude: 40.7162,
    longitude: -74.0025,
    category: 'Water Services',
    severity: 'High',
    impactScore: 82,
    priority: 'High',
    department: 'Water Services',
    estimatedResolution: '24 hours',
    status: 'Reported',
    createdAt: '2026-07-15T09:15:00Z',
    confidence: 89,
    impactReason: 'Standing water can damage pavement, create slip hazards, and waste municipal resources.',
    aiExplanation: 'The image indicates active water accumulation in a pedestrian area with drainage overflow risk.',
    potentialConsequences: 'If ignored, the leak may undermine pavement, increase slip injuries, and waste treated water.',
    immediateAction: 'Dispatch water services to isolate the leak and place temporary pedestrian warnings.',
    communityConfidence: 69,
    confirmations: 6,
    evidenceCount: 2,
    safetyRisk: 'Medium',
    accessibilityImpact: 'High',
    environmentalImpact: 'Medium',
    peopleAffected: 'Estimated 180+',
  },
];

export const demoAnalysis = demoReports[0];
